import React, {useState} from "react";
import StaffTableRow from "./StaffTableRow";

function StaffPage() {

    const[people, setPeople] = useState([])
    const fetchData = () => {
        fetch ('https://randomuser.me/api/?results=10')
        .then((res) => res.json())
        .then((res) => {
            setPeople(res.results);
        })
        .catch(() => {
            alert("random user generator call is not working properly")
        });
    };

    return (
    <>
        <h2>Staff</h2>
            <article>
                <p>
                Populate the table from data randomly generated by an API
                </p>
                <button id="populateTable" onClick={fetchData}>Populate Table</button>
                <table>
                    <caption>Our team</caption>
                    <thead>
                        <tr>
                            <th>Portrait</th>
                            <th>Name/Email</th>
                            <th>Telephone</th>
                            <th>City</th>
                        </tr>
                    </thead>
                    <tbody id="peopleTableBody">
                        {people.map((person, index) => 
                            <StaffTableRow person={person} key={index}/>
                        )}
                    </tbody>
                </table>
            </article>
    </>
    )
}

export default StaffPage

